//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<examcenter> examcenters { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<invigilator> invigilators { get; set; }
        public virtual DbSet<arrangements> arrangements { get; set; }
    }
}
